# RobAI Tools Documentation
# Jekyll configuration for GitHub Pages with Just the Docs theme

# Site settings
title: RobAI Tools
description: Comprehensive documentation for the RobAI Tools ecosystem
baseurl: "/robaitools"
url: "https://rob-p-smith.github.io"

# Theme configuration
remote_theme: just-the-docs/just-the-docs@v0.10.0

# Color scheme (supports light/dark mode)
color_scheme: nil

# Logo and search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_sort: case_insensitive
nav_fold: true

# Heading anchor links
heading_anchors: true

# Aux links (top right)
aux_links:
  "GitHub Repository":
    - "https://github.com/Rob-P-Smith/robaitools"

aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2025 RobAI Tools. Distributed under the MIT License."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# GA tracking (optional - add your tracking ID)
# ga_tracking: UA-XXXXXXXX-X

# Mermaid diagrams support
mermaid:
  version: "10.6.1"

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
